---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Ensures GPG is installed
      ansible.builtin.apt:
        name: gnupg
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - signal
