---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Ensures dependencies are installed
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      when: ansible_os_family == 'Debian'
      with_items:
        - gnupg
        - libdrm-dev
        - libgbm-dev
        - libxshmfence1

  tasks:
    - name: "Include staticdev.signal"
      ansible.builtin.include_role:
        name: "staticdev.signal"
